@startuml 

actor "User" as user
participant Controller
participant Account
participant UserDetail
participant Promocode

== Home == 

== ดึงรายการจอง ==

user -> Controller : get user acc
activate Controller
Controller -> Account : get booking list
activate Account


Account --> Controller : return booking


deactivate Account
Controller --> user : display history
deactivate Controller

== ดึงโปรโมชั่น ==

user -> Controller : get user acc
activate Controller
Controller -> Account : get promocode
activate Account
Account -> Promocode : get available promocode
activate Promocode
Promocode --> Account : return promocode
deactivate Promocode
Account --> Controller : return promocode list
deactivate Account
Controller --> user : display promocodes
deactivate Controller

== ใช้แต้มสะสม ==

user -> Controller : get user acc
activate Controller
Controller -> Account : use points
activate Account

opt กรณีแต้มพอ
    Account -> Promocode : apply discount
    activate Promocode
    Promocode --> Account : return updated discount
    deactivate Promocode
    Account --> Controller : return updated points
else กรณีแต้มไม่พอ
    Account --> Controller : return "insufficient points"
end

deactivate Account
Controller --> user : updated points shown
deactivate Controller

== แก้ไขโปรไฟล์ ==

user -> Controller : get user acc
activate Controller
Controller -> Account : get user details
activate Account
Account -> UserDetail : fetch details
activate UserDetail
UserDetail --> Account : return details
deactivate UserDetail
Account --> Controller : return user details
deactivate Account
Controller --> user : display profile info
deactivate Controller

user -> Controller : edit profile
activate Controller
Controller -> Account : update profile
activate Account
Account -> UserDetail : modify user details
activate UserDetail
UserDetail --> Account : update successful
deactivate UserDetail
Account --> Controller : success
deactivate Account
Controller --> user : profile updated
deactivate Controller

== เปลี่ยนรหัสผ่าน ==

user -> Controller : get user acc
activate Controller
Controller -> Account : change password
activate Account

alt ตรวจสอบรหัสผ่านเก่า
    Account -> Account : verify old password
    opt กรณีรหัสผ่านถูกต้อง
        Account -> Account : update new password
        Account --> Controller : success
    else กรณีรหัสผิด
        Account --> Controller : return "incorrect password"
    end
end

deactivate Account
Controller --> user : password updated
deactivate Controller

== ออกจากระบบ ==

user -> Controller : get user acc
activate Controller
Controller -> Account : Logout()
activate Account
Account --> Controller : success
deactivate Account
Controller --> user : logged out
deactivate Controller

@enduml