@startuml

actor "User" as user
participant Flight
participant FliteRoute
participant PassengerType
participant Promocode
participant SeatClass
participant ExtraServices
participant Booking
participant payment
participant "Check-in Database" as checkinDB

== ค้นหาเที่ยวบินและรายละเอียด ==
loop 
   user -> Flight: Search Flight
   activate Flight #BBBBBB
   Flight -> FliteRoute: Fetch available flights
   activate FliteRoute #FFBBBB
   FliteRoute ->PassengerType: Select Passenger Details
   deactivate FliteRoute 
   activate PassengerType #FFBBBB
   PassengerType -> Promocode : Enter Promocode
   deactivate PassengerType
   activate Promocode #FFBBBB
   Promocode --> Flight: Return flight list
   deactivate Promocode
   Flight --> user: Display flight options
   deactivate Flight
end

== เลือกเที่ยวบินและประเภทที่นั่ง ==


== ข้อมูลผู้โดยสาร ==


== บริการเสริม ==


== ทำการจองและชำระเงิน ==


== จัดการการจอง (เปลี่ยน/ยกเลิกเที่ยวบิน) ==


== เช็คอินออนไลน์ ==



@enduml