@startuml
actor "User" as user
participant Account
participant Controller
participant Booking
participant FlightRoute
participant Seat
participant Payment

== Manage Booking (Edit_booking/Cancel_booking) ==

user -> Controller: Select Edit_booking/Cancel_booking
activate Controller #BBBBBB
alt Edit_booking
    Controller -> Booking: edit_booking ()
    activate Booking #BBBBBB
    Booking -> FlightRoute: get_available_flight ()
    activate FlightRoute #BBBBBB
    FlightRoute --> Booking: Return available_flights []
    deactivate FlightRoute

    Booking -> Seat:get_available_seat ()
    activate Seat #BBBBBB
    Seat --> Booking:Return available_seat []
    deactivate Seat
    Booking --> Controller: Return Flight_Updated
    deactivate Booking

else Cancel_booking
    Controller -> Booking: cancel_booking ()
    activate Booking #BBBBBB
    Booking -> Payment: refund_payment ()
    activate Payment #BBBBBB
    Payment --> Booking: Return Refund_Processed
    deactivate Payment
    Booking --> Controller: Return cancel_booking
    deactivate Booking
end

Controller -->user: Edit_booking/Cancel_booking Confirmed
deactivate Controller
@enduml
