@startuml userCaseDiagram

left to right direction
actor "User" as user
rectangle flight {
   usecase "Search" as search
   usecase "Manage booking" as managebooking
   usecase "Promocode" as promocode
   usecase "Payment" as payment
   usecase "Login" as login
   usecase "register" as register
   usecase "Select seat&luggage" as selectseats
   usecase "Select flight&type" as selectflight
   usecase "Passenger Info"as passengerinfo
   usecase "Homepage"  as homepage
   usecase "Change Password"  as changepassword
}
user -- register 
register --> login:include
login --> homepage:include
search -up-> homepage:extend
selectflight -up-> search:extend
selectseats -up-> selectflight:extend
passengerinfo -up-> selectseats:extend
payment -up-> passengerinfo:extend
managebooking -up-> homepage:extend
promocode -up-> homepage:extend
changepassword -up-> homepage:extend
@enduml