@startuml

actor "User" as user
participant Controller
participant Account

== Login Page ==

   user -> Controller: Turn into the system
   activate Controller #BBBBBB
   alt User have an account
      Controller --> Account: login() ,login_page
      activate Account #FFBBBB
      Account -> Account: is_corret()
      Account --> Controller: user login
      Controller --> user : login successful
      deactivate Account
   else User is not have an account
      Controller --> Account: register()
      activate Account #FFBBBB
      Account -> Account: is_success()
      Account --> Controller: register success
      Controller --> user : register successful
      user -> Controller :Auto turn into system
      Controller --> Account: login() ,login_page
      Account -> Account: is_corret()
      Account --> Controller: user login
      Controller --> user : login successful
      deactivate Account
   end

   Controller -> Controller: is_login()
   Controller -> Account: login success
   activate Account #FFBBBB
   Account -> Account: return Home Page
   Account --> Controller: Home Page
   deactivate Account
   Controller --> user : display_home_page()
   deactivate Controller

@enduml