@startuml SelectSeat
actor "User" as user
participant Account
participant Controller
participant FlightRoute

loop
    user -> Controller: select_seat()
    activate Controller #BBBBBB
    Controller -> Controller: check seat availability
    Controller -> user: display available seats
    user -> Controller: choose_seat(seat_number)
    Controller -> FlightRoute: reserve_seat(seat_number)
    FlightRoute -> Controller: seat_reserved()
    Controller -> user: confirm_seat_selection()
    deactivate Controller
end

@enduml
