@startuml SelectFlight
actor "User" as user
participant Account
participant Controller
participant FlightRoute


loop
    user -> Controller: select_flight()
    activate Controller #BBBBBB
    Controller -> Controller: display seat classes (Chern Lite, Chern Extra, Chern MAX)
    Controller --> user: show_seat_classes()
    deactivate Controller
end

@enduml